### ISSUE TITLE
Chromatogram documentation is missing the actual data

### ISSUE THREAD

**Issue by Mailaender** [AnIML/techniques#16]
https://apps.bssn-software.de/techniquedocs/out/chromatography/ is comprehensive. However, I am missing storage fields for retention time, intensity/abundance and ions consisting of mass and abundance for mass spectrometry coupled with chromatography. Take a look at the standards defined by @HUPO-PSI who solved this some time ago.

**Comment by burkhardschaefer** [comment]
The chromatography technique only describes the separation, not the detection. Detectors have their own technique definitions.

For example, mass spec chromatograms (TICs, XICs, BPCs, etc.) are covered in `ms-trace.atdd`.

**Comment by Mailaender** [comment]
https://apps.bssn-software.de/techniquedocs/out/fid-trace/ works but https://apps.bssn-software.de/techniquedocs/out/ms-trace is not available. :(

**Comment by Mailaender** [comment]
Reading https://github.com/AnIML/techniques/blob/master/ms-trace.atdd is actually easier than the compiled HTML.
