### ISSUE TITLE
fix Units

### ISSUE THREAD

**Issue by Matthias-Breuer-iCD** [AnIML/techniques#3]
please fix ug_per_mL: 

&lt;!ENTITY mg_per_mL "&lt;Unit label='mg/mL'&gt;&lt;SIUnit exponent='1' factor='1e-6'&gt;kg&lt;/SIUnit&gt;&lt;SIUnit exponent='-3' factor='1e-6'&gt;m&lt;/SIUnit&gt;&lt;/Unit&gt;"&gt;
&lt;!ENTITY ug_per_mL "&lt;Unit label='µg/mL'&gt;&lt;SIUnit exponent='1' factor='**1e-9**'&gt;kg&lt;/SIUnit&gt;&lt;SIUnit exponent='-3' factor='1e-6'&gt;m&lt;/SIUnit&gt;&lt;/Unit&gt;"&gt;
&lt;!ENTITY ng_per_mL "&lt;Unit label='ng/mL'&gt;&lt;SIUnit exponent='1' factor='1e-12'&gt;kg&lt;/SIUnit&gt;&lt;SIUnit exponent='-3' factor='1e-6'&gt;m&lt;/SIUnit&gt;&lt;/Unit&gt;"&gt;

**Comment by burkhardschaefer** [comment]
Thanks, @Matthias-Breuer-iCD, good catch.
